### ISSUE TITLE
err ssl protocol error

### ISSUE THREAD

**Issue by hunao0221** [kenzok8/Trojan#1]
装好之后，用clash可以ping通，但是访问网页一直报这个错，err ssl protocol error, 是证书的问题吗？

**Comment by kenzok8** [comment]
clash编译没问题的，是不是你编译缺少openssl？

**Comment by hunao0221** [comment]
> clash编译没问题的，是不是你编译缺少openssl？
> […](#)
> 在 2020年4月20日，08:04，胡闹 ***@***.***> 写道： ﻿ 装好之后，用clash可以ping通，但是访问网页一直报这个错，err ssl protocol error, 是证书的问题吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

重新安装了好几次都不行，日志中也没有发现错误，后来没办法换成了centos7，一次就成功了。之前用的Ubuntu18
