### ISSUE TITLE
证书签发失败。请问如何解决？谢谢

### ISSUE THREAD

**Issue by qnyblog** [kenzok8/Trojan#6]
使用
1. 安装trojan-go + nginx +tls
或者
2. 安装trojan-go + caddy +tls
都会出现以下问题。请问如何解决？谢谢

[Sat 26 Jun 2021 07:29:18 PM CST] acme.sh is using ZeroSSL as default CA now.
[Sat 26 Jun 2021 07:29:18 PM CST] Please update your account with an email address first.
[Sat 26 Jun 2021 07:29:18 PM CST] acme.sh --register-account -m my@example.com
[Sat 26 Jun 2021 07:29:18 PM CST] See: https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA
[Sat 26 Jun 2021 07:29:18 PM CST] Please add '--debug' or '--log' to check more details.
[Sat 26 Jun 2021 07:29:18 PM CST] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[错误] TLS 证书生成失败

**Comment by 23hp** [comment]
acme.sh --register-account -m 你的邮箱
祝顺利

**Comment by Eustiya** [comment]
@23hp -bash: acme.sh: command not found

**Comment by chchia** [comment]
./acme.sh --register-account -m 你的邮箱
